builders:
  images_resources:
    import: 'package:sresources_generator/generator/_s_builder.dart'
    builder_factories: ['sResourceBuilder']
    build_extensions: { '$package$': ['.gen.dart'] }
    auto_apply: dependents
    build_to: source

