name: sresources_generator
description: "A library use for generate colors,images,language texts classes etc. Also support GetX i18n and route classes generation."
version: 1.0.2
homepage: https://github.com/Rico-9617/sresources_generator/tree/main/example
repository: https://github.com/Rico-9617/sresources_generator
documentation: https://github.com/Rico-9617/sresources_generator/tree/main/sresources_generator
issue_tracker: https://github.com/Rico-9617/sresources_generator/issues

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  build: ^2.4.1
  glob: ^2.1.2
  path: ^1.9.0
  xml2json: ^6.2.3
  yaml: ^3.1.2
  analyzer: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:

  uses-material-design: true
